auction/auth.py
from flask import ( 
    Blueprint, flash, render_template, request, url_for, redirect
) 
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user
from . import db



bp = Blueprint('auth', __name__)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()):
        #get data from form
        user_name = login_form.user_name.data
        password = login_form.password.data

        #check to see if user already exists
        u1 = User.query.filter_by(username=user_name).first()

        #if the user does not exist return an error
        if u1 is None:
            error='User Name does not exist. Check your spelling or click the register link below if you do not have an account.'

        #if the password does not match return an error
        elif not check_password_hash(u1.password_hash, password):
            error='Incorrect password'

        #if no errors occur, log user in and redirect to page
        if error is None:
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    if (register.validate_on_submit()):
        usern = register.user_name.data
        passw = register.password.data
        email = register.email_id.data
        phone = register.phone.data
        addr = register.address.data

        u1 = User.query.filter_by(username=usern).first()
        if u1:
            flash('User name already in use. Please try another.')
            return redirect(url_for('auth.register'))

        #hashing the users password
        passw_hash = generate_password_hash(passw)

        #creating new user
        new_user = User(username=usern, password_hash=passw_hash, email=email, phone=phone, address=addr)

        #add new user to database
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for("main.index"))
    
    else:
        return render_template('user.html', form=register, heading='Register')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return 'You have been signed out'

auction/views.py
from flask import Blueprint
from flask import render_template, url_for, request, redirect
from .models import Products, User
from . import db
from flask_wtf import FlaskForm
from flask_login import current_user
from .forms import Additem
from flask_bootstrap import Bootstrap


bp = Blueprint('main', __name__)
#Bootstrap(bp)
@bp.route('/') #landing page
def index():    #view function
    products = Products.query.all()
    return render_template('LandingPage.html', products=products)

#@bp.route('/createitem')#item creation page
#def createitem():    #view function
#    return render_template('ItemCreation.html')

@bp.route('/view_items', methods=['GET', 'POST'])#item details page
def view_items():    #view function
    products = Products.query.all()
    wishlist = Additem()
    if (wishlist.validate_on_submit()):
        print('New wishlist item added')
        
        db.session.commit()
        return redirect(url_for('main.index'))
    
    
    return render_template('ItemDetailsPage.html', products = products, id=id, form=wishlist)

@bp.route('/user')#user page
def user():    #view function
    return render_template('user.html')

@bp.route('/userwishlist')#item wishlist page
def userwishlist():    #view function
    return render_template('UserWishlist.html')

@bp.app_errorhandler(404)#handles 404 errors
def not_found(e): #error view function
    return render_template('404_Error.html'),404

@bp.app_errorhandler(500)#handles 404 errors
def not_found(e): #error view function
    return render_template('500_Error.html'),500

auction/templates/404_Error.html
{% extends 'base.html' %}

{% block content %}
		
		<main>
		<h1>404 Error!</h1>
		<br>
		<h2>Page not found</h2>
		</main>
{% endblock %}

auction/templates/500_Error.html
{% extends 'base.html' %}

{% block content %}
		
		<main>
		<h1>500 Error!</h1>
		<br>
		<h2>Internal Server Error</h2>
		</main>
{% endblock %}

auction/templates/ItemCreation.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  {% if current_user.is_authenticated %} 
  <div class="container">

    <div class="row mt-5">
      <div class="col-md-12">

        <h1>Create New Listing:</h1>

		{{wtf.quick_form(form)}}
        
      </div>
    </div>
  </div>

  {% else %} 

  <div class="container">

    <div class="row mt-5">
      <div class="col-md-12">

        <h1>You must be logged in to access this function.</h1>
        <p>Not signed in? <a href="{{ url_for('auth.login') }}">Click here to login.</a>.</p>
        
      </div>
    </div>
  </div>

  {% endif %} 

{% endblock %}

auction/templates/ItemDetailsPage.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
		<main>
			<div class="container-fluid">
				<div class="row item-detail text-dark container-fluid">
					<div class="col-md-3">
						<h3>Product Name</h3>
						<h4> {{products.product_name}}</h4>
						<h3>Product Image</h3>
						<img class="d-block w-100" src="{{ products.product_image_ }}" alt="Item Picture">
						<h3>Product Description</h3>
						<p> {{ products.product_description }}</p>
						<h3>Product Category</h3>
						<p>{{ products.product_category }}</p>
						<h3>Product Price</h3>
						<p>${{ products.product_bidstart }}</p>
						<a href="{{ url_for('product.create') }}" class="btn btn-secondary btn-lg active" role="button">Create New Listing</a>
						<a href="{{ url_for('product.bid') }}" class="btn btn-secondary btn-lg active" role="button">Bid on Item</a>

					
							</div>
							</div>
							</div>
						<div class="dropdown" style="margin-top: 10px">
							<div aria-haspopup="true" aria-expanded="false" class="col-sm-1">
								{{ wtf.quick_form(form)}}
							</div>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								<a class="dropdown-item active" href="#">Wishlist 1</a>
								<a class="dropdown-item" href="#">Wishlist 2</a>
								<a class="dropdown-item" href="#">Wishlist 3</a>
							</div>
							</div>
					</div>
					<div class="col-md-3 my-auto">
					<h3> Current Bidders</h3>
							<ul class="list-group text-dark">
								<li class="list-group-item"> Bidder 1 - $150.55</li>
								<li class="list-group-item"> Bidder 2 - $150.00</li>
							</ul>
						<h3>Bidding Information</h3>
							<ul class="list-group text-dark">
								<li class="list-group-item"> {{ products_bidstart }}</li>
								<li class="list-group-item"> Latest Bid: $150.55</li>
							</ul>
					<div class="card text-dark" style="margin-top:15px">
						<div class="card-header">
							Comments
						</div>
						<div class="card-body">
							<blockquote class="blockquote mb-0">
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
							<footer class="blockquote-footer">@1:03pm today by user <cite title="Source Title">Nick Allan</cite></footer>
							</blockquote>
							<blockquote class="blockquote mb-0">
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
							<footer class="blockquote-footer">@11:49am today by user <cite title="Source Title">John Doe</cite></footer>
							</blockquote>
						</div>
						<div class="card-header">
							Write a Comment
						</div>
						<div class="card-body" style="margin-bottom: 15px">
							<form>
							<div class="form-group">
								<textarea class="form-control" id="comment" rows="3">Click in me and start typing</textarea>
							</div>
							<button type="submit" class="btn btn-primary">Submit</button>
							</form>
						</div>
						</div>
					</div>
				</div>
			</div>
			<div style="height:100vh">
			</div>
		</main>
		
{% endblock %}

auction/templates/LandingPage.html
{% extends 'base.html' %}

{% block content %}
		
		<main>
		<div class="jumbotron">
			<h1 class="display-4">How To Get Started - Please Read</h1>
			<p class="lead">Welome to the website! Please login to access the features of the website, to do this please go to the top of the screen and go to 'Account Settings' then login. If you do not have an account choose the register option.</p>
			<hr class="my-4">
			<p> Once you have registered and signed in, you will have access to look at listed items as well as the ability to list your own items. If you are looking for a specific item you can search by the categories at the top of the page, just click on the one you like. To get started by creating your own listing click the button below.</p>
			<a class="btn btn-primary btn-lg" href="{{ url_for('product.create')}}" role="button">Create a Listing</a>
		</div>
			<div class="container-fluid" style="margin-bottom: 15px">
					<div class="row">
						<div class="col-md-3">
						<h1>
						Top 5 Featured Items
						</h1>
						<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
							<ol class="carousel-indicators">
								<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
								<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
								<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
								<li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
								<li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
							</ol>
							<div class="carousel-inner">
								<div class="carousel-item active">
									<img class="d-block w-100" src="img/image1.jpg" alt="First Item">
									<div class="carousel-caption d-none d-md-block">
										<h5>Featured Item 1</h5>
										<p> Current Bidding Price: $122.00</p>
										<p> Active Bidders: 32</p>
									</div>
								</div>
								<div class="carousel-item">
									<img class="d-block w-100" src="img/image2.jpg" alt="Second Item">
									<div class="carousel-caption d-none d-md-block">
										<h5>Featured Item 2</h5>
										<p> Current Bidding Price: $142.00</p>
										<p> Active Bidders: 54</p>
									</div>
								</div>
								<div class="carousel-item">
									<img class="d-block w-100" src="img/image3.jpg" alt="Third Item">
									<div class="carousel-caption d-none d-md-block">
										<h5>Featured Item 3</h5>
										<p> Current Bidding Price: $452.50</p>
										<p> Active Bidders: 187</p>
									</div>
								</div>
								<div class="carousel-item">
									<img class="d-block w-100" src="img/image4.jpg" alt="Fourth Item">
									<div class="carousel-caption d-none d-md-block">
										<h5>Featured Item 4</h5>
										<p> Current Bidding Price: $200.00</p>
										<p> Active Bidders: 83</p>
									</div>
								</div>
								<div class="carousel-item">
									<img class="d-block w-100" src="img/image5.jpg" alt="Fifth Item">
									<div class="carousel-caption d-none d-md-block">
										<h5>Featured Item 5</h5>
										<p> Current Bidding Price: $105.00</p>
										<p> Active Bidders: 90</p>
									</div>
								</div>
							</div>
						<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
							<span class="carousel-control-prev-icon" aria-hidden="true"></span>
							<span class="sr-only">Previous</span>
						</a>
						<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
							<span class="carousel-control-next-icon" aria-hidden="true"></span>
							<span class="sr-only">Next</span>
						</a>
						</div>
						</div>
						<div class="col-md-3">
						<h1> Click to View Item</h1>
						<!--listed items for featured items-->
							<ul class="list-group">
								<a href="{{ url_for('product.view', id=products.id) }}" class="list-group-item list-group-item-action"> Featured Item 1</a>
								<a href="{{ url_for('main.view_items', id=products.id) }}" class="list-group-item list-group-item-action"> Featured Item 2</a>
								<a href="{{ url_for('main.view_items', id=products.id) }}" class="list-group-item list-group-item-action"> Featured Item 3</a>
								<a href="{{ url_for('main.view_items', id=products.id) }}" class="list-group-item list-group-item-action"> Featured Item 4</a>
								<a href="{{ url_for('main.view_items', id=products.id) }}" class="list-group-item list-group-item-action"> Featured Item 5</a>
						</div>
					</div>
			</div>
		</main>
{% endblock %}

auction/templates/UserWishlist.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
		
		<main>
			<div class="container-fluid text-dark" style="margin-bottom: 15px; width 100vh">
				<div class="row">
					<div class="col-md-3">
						<h4>My Wishlist</h4>
						<p><h5>Wishlist 1</h5></p>
							<ul class="list-inline d-flex justify-content-between align-items-center">
								<li class="list-inline-item">Product</li>
								<li class="list-inline-item">Date</li>
								<li class="list-inline-item">Bid Status</li>
								<li class="list-inline-item">Img</li>
							</ul>
							<ul class="list-inline listing-preset d-flex justify-content-between align-items-center">
								<li class="list-inline-item">Featured Item 1</li>
								<li class="list-inline-item">12/09/2020 @2pm</li>
								<li class="list-inline-item">current: $150.55</li>
									<div class="image-thumbnail">
										<img src="img/image1.jpg" class="img-fluid" alt="Featured Item 1">
									</div>
								</li>
								
							</ul>
							<ul class="list-inline listing-preset">
								<a href="#" <li class="list-inline-item listing-aligner">Add More Items</li></a>
							</ul>
							<div style="height:100vh">
							</div>
					</div>
				</div>
			</div>
		</main>
{% endblock %}
		

auction/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	
	<link rel="stylesheet" href="css/style.css">
    <title>Landing Page</title>
  </head>
  <body>
    
		<header>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.view_items',) }}">My Items</a>
						</li>
						<li class="nav-item">
						<a class="nav-link" href="{{ url_for('product.create') }}">Create Listing</a>
					    </li>
						<li class="nav-item">
							<a class="nav-item nav-link" href="{{ url_for('main.userwishlist') }}">My Wishlists</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Account Settings
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{{ url_for('auth.login') }}"> Log In </a>
                                <a class="dropdown-item" href="{{ url_for('auth.register') }}"> Register </a>
                                <a class="dropdown-item" href="{{ url_for('auth.logout') }}"> Sign Out </a>
								</div>
						</li>
					</ul>
				</div>
				<form class="form-inline">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</nav>
			
				<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-center-between">
					<a class="navbar-brand" href="#">Categories</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					
					<div class="collapse navbar-collapse" id="navbarNav">
						<ul class="navbar-nav">
							<li class="nav-item">
								<a class="nav-link" href="#">Paintings</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Photography</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Sculpting</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Calligraphy</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Illustrations</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Printmaking</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">Graphic Design</a>
							</li>
						</ul>
					</div>
				</nav>
        
        {%block header %}
        {% endblock %}

		</header>
        
        {% block content %}
        {% endblock %}
		
		<footer>
			<div class="container-fluid">
				<div class="row footer-row text-white">
					<div class="col-12">
						<ul class="list-inline">
							<li class="list-inline-item">Lorem ipsum</li>
							<li class="list-inline-item">Lorem ipsum</li>
							<li class="list-inline-item">Lorem ipsum</li>
						</ul>
					</div>
				</div>
				<div class="row footer-row text-white">
					<div class="col-6">
					Contact Us
					</div>
					<div class="col-6">
						<ul class="list-inline">
							<li class="list-inline-item">Email</li>
							<li class="list-inline-item">Phone Number</li>
							<li class="list-inline-item">Fax</li>
						</ul>
					</div>
				</div>
		</footer>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

auction/templates/bid.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  {% if current_user.is_authenticated %} 
  <div class="container">

    <div class="row mt-5">
      <div class="col-md-12">

        <h1>Bid on Item</h1>

        {{ wtf.quick_form(form)}}
               
        
      </div>
    </div>
  </div>

  {% else %} 

  <div class="container">

    <div class="row mt-5">
      <div class="col-md-12">

        <h1>You must be logged in to access this function.</h1>
        <p>Not signed in? <a href="{{ url_for('auth.login') }}">Click here to login.</a>.</p>
        
      </div>
    </div>
  </div>

  {% endif %} 

{% endblock %}

auction/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container content-container">
    <h2 class="text-dark border-bottom">{{heading}}</h2>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="container">
            <div class="row mt-3 mb-3">
                <div class="col md-12">
                    {% for message in messages %}
                    <div class ="alert alert-warning">{{message}}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
{% endwith %}

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6">
    {{wtf.quick_form(form)}}
    </div>
    
    <!-- When you have login form, then do show the user a link to register -->
    {% if heading|lower =='login' %}
    <div class="col-md-4">
        <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
    </div>
    {% endif %}

</div>
{% endblock %}